// Mocks generated by Mockito 5.4.4 from annotations
// in test_project/test/features/dog_info/domain/usecases/get_random_dog_info_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_project/features/dog_info/domain/entities/dog_info.dart'
    as _i2;
import 'package:test_project/features/dog_info/domain/repositories/dog_info_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDogInfo_0 extends _i1.SmartFake implements _i2.DogInfo {
  _FakeDogInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DogInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDogInfoRepository extends _i1.Mock implements _i3.DogInfoRepository {
  @override
  _i4.Future<_i2.DogInfo> getSpecificDogInfo(String? breed) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpecificDogInfo,
          [breed],
        ),
        returnValue: _i4.Future<_i2.DogInfo>.value(_FakeDogInfo_0(
          this,
          Invocation.method(
            #getSpecificDogInfo,
            [breed],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.DogInfo>.value(_FakeDogInfo_0(
          this,
          Invocation.method(
            #getSpecificDogInfo,
            [breed],
          ),
        )),
      ) as _i4.Future<_i2.DogInfo>);

  @override
  _i4.Future<_i2.DogInfo> getRandomDogInfo() => (super.noSuchMethod(
        Invocation.method(
          #getRandomDogInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.DogInfo>.value(_FakeDogInfo_0(
          this,
          Invocation.method(
            #getRandomDogInfo,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.DogInfo>.value(_FakeDogInfo_0(
          this,
          Invocation.method(
            #getRandomDogInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DogInfo>);
}
